#!/bin/bash

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v
# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do
    sudo -n true
    sleep 60
    kill -0 "$$" || exit
done 2>/dev/null &
echo "will cleanup#1"
brew cleanup
echo "will update#1"
brew update
echo "will cleanup#2"
brew cleanup
echo "will update#2"
arch -x86_64 brew update
echo "will upgrade#1"
arch -x86_64 brew upgrade
echo "will update macos#1"
softwareupdate -ia
